### ISSUE TITLE
Running on Vite: SyntaxError: Named export 'css' not found.

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-styled-components#10]
```
SyntaxError: Named export 'css' not found. The requested module 'goober' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'goober';
const { css, setup: gooberSetup } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
```

**Comment by ryansolid** [comment]
Interestingly enough goober also exports ESM, so I can only figure it's the resolution order. Looking at goober the order is pretty chaotic between different sub-module exports. And the main export seems to prioritize CJS which is weird. Hmm.. this might be something we have to address downstream with them.

**Comment by btakita** [comment]
I agree.

I was able to get it working by adding `solid-styled-components` as a git submodule in a monorepo.

**Comment by rschristian** [comment]
Goober exports ESM, but with `.js` as the extension and without `"type": "module"`.

Just an issue of not following the Node spec.
