### ISSUE TITLE
"class" props are not applied, only className

### ISSUE THREAD

**Issue by illiaChaban** [solidjs/solid-styled-components#21]
I'm using solid recommended eslint and it gives me warnings about using className as it's "react specific prop". It sounds like using "class" over "className" is a better practice, but it's not supported by this package

**Comment by ryansolid** [comment]
Ahh good point. It was sort of awkward and I sort of had to choose one and the underlying package was made for Preact.. Yeah I think `class` is more idiomatic Solid we probably should change this for the next minor version.

**Comment by illiaChaban** [comment]
it would be nice to also update the types as they don't throw errors if "class" is used. (Maybe in the next version disallow "className" or support both and then types don't need to be updated)

**Comment by dsimon-dev** [comment]
Now that solid 1.4 is out and `className` is deprecated, using `className` on a styled component with TypeScript results in a type error on `tsc`. Does anyone have a workaround for now until `class` is supported?

**Comment by ryansolid** [comment]
Ok fixed in 0.28.0
