### ISSUE TITLE
Can I pass props like `onClick` to styled components?

### ISSUE THREAD

**Issue by nikivdev** [solidjs/solid-styled-components#43]
I tried to create a `Wrapper` component like so:

```
const Wrapper = styled("div")`
  border-radius: 20px;
  padding: 30px;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  box-shadow: inset 0px 0px 0px 2px var(--color-grey);
  &:hover {
    box-shadow: inset 0px 0px 0px 2px black;
  }
  &:focus {
    box-shadow: inset 0px 0px 0px 2px black;
  }
  p {
    color: gray;
  }
```

Doesn't really matter what's inside the style. Then I tried to use `Wrapper` but also pass in custom `onClick`.

```export default function Option({
  setSelectedOption,
}: Props) {
  return (
    <Wrapper onClick={() => setSelectedOption(title)}>
```

This doesn't actually work.`setSelectedOption` never gets run. If I instead of `Wrapper` have normal `div` there, it does work.

**Comment by nikivdev** [comment]
Actually it started working for me, not sure what I was doing wrong but no longer an issue for me. 🎊

**Comment by victorivens05** [comment]
I had the same problem. In my particular case, the styled component was being created in the end of the file (using const). When I moved it to before where it was used, it worked correctly.
